name: ng-alain-delon

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

pr:
  autoCancel: true
  branches:
    exclude:
      - gh-pages

stages:
  - stage: env
    jobs:
      - job: Nodes
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.13.1'
            displayName: 'Install Node.js'

  - stage: artifacts
    jobs:
      - job: build_artifacts
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
          - script: |
              npm run build_artifacts
    dependsOn: env

  - stage: test
    jobs:
      - job: test_packages
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
          - script: |
              npm run test
              cat ./coverage-report/lcov.info | ./node_modules/.bin/codecov
          - task: PublishCodeCoverageResults@1
            displayName: 'publish code coverage results'
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage-report/cobertura-coverage.xml
              reportDirectory: $(System.DefaultWorkingDirectory)/coverage-report
              failIfCoverageEmpty: true

          - task: PublishTestResults@2
            displayName: 'publish test results'
            condition: succeededOrFailed()
            inputs:
              searchFolder: $(System.DefaultWorkingDirectory)/junit
              failTaskOnFailedTests: true
              testRunTitle: DELON
              testResultsFormat: JUnit
              testResultsFiles: '**/TESTS*.xml'
      - job: test_cli
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
          - script: npm run test:cli
    dependsOn: env

  - stage: lint
    jobs:
      - job: lint_packages
        steps:
          - task: Npm@1
            inputs:
              command: 'install'
          - script: npm run lint
    dependsOn: env
